apiVersion: v1
kind: Pod
metadata:
  name: mysql-pv
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
    - name: MYSQL_DATABASE
      value: "eazytraining"
    - name: MYSQL_USER
      value: "eazy"
    - name: MYSQL_PASSWORD
      value: "eazy"
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    ports:
    - containerPort: 3306
      name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-storage
  volumes:
  - name: mysql-storage
    persistentVolumeClaim:
      claimName: mysql-pvc

