apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-pod
spec:
  containers:
  - name: simple-webapp-container
    image: mmumshad/simple-webapp-color
    env:
    - name: APP_COLOR
      value: "red"

